### ISSUE TITLE
Military Academy faith icon bug

### ISSUE THREAD

**Issue by onleeking** [civfanatics/CQUI_Community-Edition#47] opened 2020-06-19 20:57 UTC
![nkNtxyZlcTs](https://user-images.githubusercontent.com/67170169/85178999-43798800-b299-11ea-94d4-721931e06ea2.jpg)
Look at bug. Instead faith icon u have gold icon for corps and army

**Comment by Sorxus** [comment] 2020-06-20 05:12
I was confused.  You mean "bug" offcourse...  :)

**Comment by onleeking** [comment] 2020-06-20 10:48
> I was confused. You mean "bug" offcourse... :)

yep bug xd

**Comment by onleeking** [comment] 2020-06-20 11:22
> I was confused. You mean "bug" offcourse... :)

I would also like you to make an application for setting up the mod. Very inconvenient to customize in a text document.

**Comment by alimulhuda** [comment] 2020-06-20 15:34
> I would also like you to make an application for setting up the mod. Very inconvenient to customize in a text document.

Could you elaborate on what you mean. What kind of things are you setting up? If this is a request for doing something new, then you can also create a new issue and put more details there.

**Comment by Infixo** [comment] 2020-06-21 00:28
@onleeking It is difficult to replicate your issue. Please attach a save file if possible.

**Comment by onleeking** [comment] 2020-06-21 11:50
> @onleeking It is difficult to replicate your issue. Please attach a save file if possible.




[AutoSave_0141.zip](https://github.com/civfanatics/CQUI_Community-Edition/files/4809380/AutoSave_0141.zip)

**Comment by Infixo** [comment] 2020-07-02 20:21
It contains 4 mods for MP games (BBG, BBS, hot fixes. helper). I cannot open it.

**Comment by onleeking** [comment] 2020-07-03 08:11
> It contains 4 mods for MP games (BBG, BBS, hot fixes. helper). I cannot open it.

Download this mods lol. In steam or guithub

**Comment by Infixo** [comment] 2020-07-03 10:48
I certainly won'd do that.

**Comment by onleeking** [comment] 2020-07-03 11:08
> I certainly won'd do that.

rofl. why?
it's most popular mods in community

**Comment by Infixo** [comment] 2020-07-03 17:04
Lemme think... Perhaps because this is the 2nd time you try to give me orders? Well... this is not how things work around here.

I won't give you orders. You have a choice.
a) help us fix an issue - zip them mods and attach here, so we can run the save file
b) don't help us fix an issue - and hope that someone else on the team will spend time tracking the mods and installing them or maybe fix an issue just by looking at the source code, or maybe play a few hours to recreate this specific bug.

**Comment by alimulhuda** [comment] 2020-07-05 01:17
@Infixo could this have been fixed by the fix for issue #69 ?

**Comment by Infixo** [comment] 2020-07-05 01:31
Unless there is some other hidden bug that messes up the logic then no. Corps and armies have separate code for generating buttons (separate from units and buildings).
And the buildings code is ok, icons are correct.
So, there is either some mod conflict or some specific behavior not easily seen from the code

**Comment by alimulhuda** [comment] 2020-07-05 01:49
Sorry, I'm not following. Based on the image and detailed bug description it looks like this issue is with the icon for purchasing corps and armies with faith. The description and fix for issue 69 says it fixes the icon for purchasing corps and armies with faith. I guess the title could be interpreted as some issue with the buildings code, but based on the picture it looks like the issue was shown with the purchase button for helicopter corps and army.

To me it looked like it was duplicate of 69 so I was thinking of marking it as such and closing it. Unless you had reason to think it is not a duplicate, and that's the part I'm unclear on.

**Comment by Infixo** [comment] 2020-07-05 02:12
It says Military Academy in the title, that is why I commented about buildings.
But indeed there are corps and armies icons.
Well, maybe I fixed it lol
You can close it, no objections here.

**Comment by alimulhuda** [comment] 2020-07-05 02:18
Duplicate of #69

**Closed** 2020-07-05 02:18 UTC
