### ISSUE TITLE
Investigate proper use for Air Attack and WMD with Keyboard shortcuts

### ISSUE THREAD

**Issue by the-m4a** [civfanatics/CQUI_Community-Edition#40] opened 2020-06-14 19:51 UTC
The soothsayer fix disabled the hot keys for Air Attack and WMD shortcuts because those they require additional parameters that were not being passed along.  Preferred to defer the fixes for these as it's not obvious how useful either of those commands are when they require pointing at something to attack

**Comment by the-m4a** [comment] 2020-06-14 19:58
Alimulmuda's comment from the discussion in the PR for the Soothsayer fix:

I was looking through the unmodded files for anything related to air unit rebasing. Found these functions OnMouseRebaseEnd, AirUnitReBase and OnInterfaceModeChange_ReBase in the WorldInput.lua file. Also the RequestOperation call looks like this
UnitManager.RequestOperation( pSelectedUnit, UnitOperationTypes.REBASE, tParameters);.

The stuff related to air attack also seems to be a multi-stage, multi-function process. UnitAirAttack, OnInterfaceModeChange_Air_Attack.

The WMD stuff also looks like it is multi-stage process, but I haven't tried it yet. Did you try the hotkey? Based on what I'm seeing in the base game code, it shouldn't work since it also requires a third parameter which we don't provide.

Right now I'm thinking it might not be a simple single command that we can issue, if that is the case maybe we should just remove it from this pull and work on it separately.

**Comment by the-m4a** [comment] 2020-06-15 21:54
Additionally:  investigate for Rebase and what to do with the SHIFT key that would go to the nearest City
(maybe the shift-key is an option thing that is not set to default)

**Comment by alexeyOnGitHub** [comment] 2020-06-16 04:56
do you think there are some other hotkeys for common game actions that we can also support and make configurable in the settings menu?

**Comment by the-m4a** [comment] 2020-06-16 05:20
Possibly, yeah - I don't use the keyboard much, though, so I may not be the best resource on that one :)

**Comment by Sorxus** [comment] 2020-06-20 11:55
In "Bindings" section of COUI settings there is this sentence indicating that Alt+S is for Air Attack command, but before one has to unbind keys. Could you explain that please? I couldn't make it working... :(

**Comment by alimulhuda** [comment] 2020-06-22 00:43
@Sorxus Right now the commands for Air Attack, Air Rebase, and maybe some others are not working properly. I'll be trying to add them back in hopefully soon.
The comment in that screen might be outdated. I believe what happened before some of our recent changes was that if you pressed a key that was bound to something in the unmodded game then it would try to do the CQUI action and also the unmodded game action. Right now the CQUI action will stop the base game action. So for example if you press W then CQUI will currently move the camera up. Without CQUI pressing W would default to going to the Great Works screen.

**Comment by alimulhuda** [comment] 2020-06-22 00:45
Duplicate of #22

**Comment by Sorxus** [comment] 2020-06-22 08:41
Currently there is WASD camera binding in CQUI.
Interresting is that in CQUI bindings there is that text about WASD and Alt+S for Air Attack, but you can't use key "S" for both at the same time and is a bit frustrating when you try to use it. Thatswhy my question.
Maybe it would be good idea to remove that comment in CQUI bindings if thats not the case.

**Closed** 2020-08-25 22:12 UTC
Labels: enhancement
