### ISSUE TITLE
Leader screen not showing when having Extended Diplomacy Ribbon enabled

### ISSUE THREAD

**Issue by JPAhnen** [civfanatics/CQUI_Community-Edition#30] opened 2020-06-07 14:46 UTC
**Describe the bug**
Meeting a civ for the first time, or open the leader screen by clicking on another leader's city, won't show the leader screen. Instead, all UI elements are gone and only the map is visible.

**To Reproduce**
Use CQUI and Extended Diplomancy Ribbon, click an AI's city.

**Expected behavior**
The leader screen should pop up.

**General informations**
 - OS: Windows 10
 - Expansion R+F and GS
 - Mods:
* Better Deal Window
* Better Loading Screen
* Better Report Screen
* CQUI
* Environment Skin: Sid Meier's Civilization
* Extended Diplomacy Ribbon
* Great Works Viewer
* Happiness and Growth Indicator
* Leugi's Unique District Icons
* More Lenses
* Radial Measuring Tool
* Real Era Tracker
* Removable Districts
* Starting Scout
* Vegetation Variety

**Disabling Enhanced Diplomacy Ribbons fixes the problem**

**Comment by alimulhuda** [comment] 2020-06-07 14:54
See https://github.com/civfanatics/CQUI_Community-Edition/issues/17#issuecomment-639638180

Look through the other comments in that thread. I think this is a duplicate issue. Also note that generally speaking compatibility with other mods may not be always maintained, either for lack of time or because it might break things on CQUI's end.

**Comment by alimulhuda** [comment] 2020-06-07 14:58
Duplicate of #17

**Comment by JPAhnen** [comment] 2020-06-07 20:00
Ok, I'm sorry. I saw the other issue, but it seemed to be another problem because my ribbon worked at least a bit.

**Comment by alimulhuda** [comment] 2020-06-07 20:13
@JPAhnen No worries. The fix I did for that issue should also fix your issue. So if you have time it would be helpful if you followed the instruction in that comment and tried it out. After you try it out you can leave a comment and let us know how it worked out.

**Closed** 2020-06-08 04:05 UTC
