### ISSUE TITLE
Unassigned Citizens Icon is bugged with Vanilla City Banners

### ISSUE THREAD

**Issue by Gliptal** [civfanatics/CQUI_Community-Edition#236] opened 2021-01-18 22:11 UTC
Taking this screenshot as reference:

![civ6](https://user-images.githubusercontent.com/3907646/104966499-4da36680-59e1-11eb-87f0-e58971a3eac3.png)

- The city banner I'm getting seems remarkably different to [the supposed one](https://i.imgur.com/Xdt33Nw.mp4). Notice the missing healthbar and the population being on the left rather than the right.
- What does the colored overlay (green on two tiles here) indicate? They're connected to the "Citizen Management on Hover" option, but I can find no explanation on the colors meaning. Is there a way to disable it? If it simply indicates which tiles are being worked on, it seems both distracting and redundant (that information is already conveyed by the icons).
- I manually set the only available citizen to work on the tile: why is the exclamation point icon still showing in the city banner? Shouldn't that show up only if one or more citizens are being assigned by the AI?

Thanks for working on this mod! I just started playing Civ6 and found the vanilla interface really lacking.

**Comment by the-m4a** [comment] 2021-01-21 05:38
The city banner you're seeing is the one that shows up when playing without the expansions (the "standard rules").  For some reason Firaxis changed it with the Rise and Fall expansion pack, and kept that same banner in place with the Gathering Storm expansion.

That overlay is (somehow, I'm not entirely sure) showing you both the city information and the actions the builder can take.
![gif](https://i.imgur.com/848i46L.gif).  
Normally when you have clicked on a city, it turns that center hex that light green color.  Similarly, when you have a builder that can do certain things, it will highlight hexes where it can do said things.  If I remember correct, Green is mine, blue is chop, grey is irrigate, and pink is do something with luxury/resource.  I think you see green with the furs icon there because you haven't yet researched Animal Husbandry.  When able to get furs from the plot, it turns pink:
![image](https://user-images.githubusercontent.com/8787640/105284233-ee6f5e80-5b66-11eb-8b1b-fdeb9797f20b.png)

That last one is a bug, it seems!  That feature is off by default, and I don't personally use it so I am guilty of not checking it recently.
![image](https://user-images.githubusercontent.com/8787640/105284627-b583b980-5b67-11eb-8447-c962df37e76e.png)

While the first two are expected conditions (save for somehow showing the city panels while also having the builder selected, which I can't reproduce), that third one certainly is not.  Thank you for finding it!

**Comment by the-m4a** [comment] 2021-01-21 05:45
The maintaining 2 separate code paths for vanilla and the expansions strikes again here:  this bug only appears in the vanilla version.  Works okay with the expansions:
![gif](https://i.imgur.com/VU2sjt6.gif)

Also updated the title of this issue so this can be tracked

**Comment by Gliptal** [comment] 2021-01-21 08:26
I see what you mean with the coloring, makes sense.

**Comment by the-m4a** [comment] 2021-01-28 08:26
I have the fix for this in a branch I just pushed up, I'll create a PR after completing the one for the Inline City State quests

**Comment by Gliptal** [comment] 2021-01-30 01:15
Played a few hours tonight and I believe this is fixed.

**Comment by the-m4a** [comment] 2021-01-30 05:35
cool, thanks for verifying!

**Closed by the-m4a** 2021-01-30 05:35 UTC
Labels: base-game-only
